requireModuleInFile rootPath.models, 'model-base'
requireModuleInFile rootPath.models, 'redis-ORM'
requireModuleInFile rootPath.models, 'tweet'
requireModuleInFile rootPath.models, 'twitter-user'
requireModuleInFile rootPath.models, 'streamer'
